name: Tests
on: push

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-26-intel]
        python-version: ["3.8", "3.10", "3.12", "3.14"]
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - run: sudo apt-get update && sudo apt-get install -y libev-dev
        if: matrix.os == 'ubuntu-latest'
      - run: brew install libev
        if: matrix.os == 'macos-26-intel'
      - name: Build
        run: |
          pip install setuptools
          pip install .
          cd /tmp
          python -c "import bjoern"
        shell: bash -ex {0}
      - name: Run tests
        run: |
          pip install requests
          python tests/interrupt-during-request.py
          python tests/keep-alive-behaviour.py
          python tests/test_wsgi_compliance.py
          python tests/expect100.py
        shell: bash -ex {0}

